[swipe.commands.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = "ydotool key alt+right"
right = "ydotool key alt+left"

[swipe.commands.four]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = "swaymsg 'workspace next'"
right = "swaymsg 'workspace prev'"

[pinch.commands]
in = ""
out = ""

[pinch.settings]
threshold = 0.25
one_shot = false


[swipe.settings]
threshold = 0.5
one_shot = true
trigger_on_release = false
